#goal definition
uint8   action_id 
---
#result definition
uint8   action_id
string  result
---
#feedback
uint8   action_id
string  status






################# action_id
#	"1 - Reach Straight Neck Position"
#	"2 - Invitation Left"
#	"3 - Invitation Right"
#	"4 - Give a Bow"
#	"5 - Surprise Expression"
#	"6 - Bend Forward"
#	"7 - Bend Back"
#	"8 - Bend Left"
#	"9 - Bend Right"
#	"0 - Test Led"