- id: 0
  name: AD
  position: [-2.0, -1.54, 0]
  orientation: [-0.73, 0.68]

- id: 1
  name: AS
  position: [3.59, -0.24, 0]
  orientation: [-0.67, 0.73]

- id: 2
  name: base
  position: [-0.014, 0.0, 0]
  orientation: [0.70, 0.70]
