- id: 0
  name: airlab
  position: [-3.97, -6.54, 0]
  orientation: [0.1, 0.1]
 
- id: 1
  name: google
  position: [-4.41, 5.35, 0]
  orientation: [0.1, 0.1]

- id: 2
  name: base
  position: [4.73, 7.52, 0]
  orientation: [0.1, 0.1]
