- id: 0
  name: airlab
  position: [-3.587, -7.08, 0]
  orientation: [-0.71, 0.70]

- id: 1
  name: google
  position: [3.77, -5.3, 0]
  orientation: [-0.69, 0.72]

- id: 2
  name: base
  position: [4.88, 7.53, 0]
  orientation: [0.99, 5.12]

