/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/vrep/vrep_common/srv/simRosGetDialogResult.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSGETDIALOGRESULT_H
#define VREP_COMMON_SERVICE_SIMROSGETDIALOGRESULT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosGetDialogResultRequest_ {
  typedef simRosGetDialogResultRequest_<ContainerAllocator> Type;

  simRosGetDialogResultRequest_()
  : dialogHandle(0)
  {
  }

  simRosGetDialogResultRequest_(const ContainerAllocator& _alloc)
  : dialogHandle(0)
  {
  }

  typedef int32_t _dialogHandle_type;
  int32_t dialogHandle;


  typedef boost::shared_ptr< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosGetDialogResultRequest
typedef  ::vrep_common::simRosGetDialogResultRequest_<std::allocator<void> > simRosGetDialogResultRequest;

typedef boost::shared_ptr< ::vrep_common::simRosGetDialogResultRequest> simRosGetDialogResultRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosGetDialogResultRequest const> simRosGetDialogResultRequestConstPtr;


template <class ContainerAllocator>
struct simRosGetDialogResultResponse_ {
  typedef simRosGetDialogResultResponse_<ContainerAllocator> Type;

  simRosGetDialogResultResponse_()
  : result(0)
  {
  }

  simRosGetDialogResultResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosGetDialogResultResponse
typedef  ::vrep_common::simRosGetDialogResultResponse_<std::allocator<void> > simRosGetDialogResultResponse;

typedef boost::shared_ptr< ::vrep_common::simRosGetDialogResultResponse> simRosGetDialogResultResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosGetDialogResultResponse const> simRosGetDialogResultResponseConstPtr;

struct simRosGetDialogResult
{

typedef simRosGetDialogResultRequest Request;
typedef simRosGetDialogResultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosGetDialogResult
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "290f4bd47ce8d0f7c78c1d510052331a";
  }

  static const char* value(const  ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x290f4bd47ce8d0f7ULL;
  static const uint64_t static_value2 = 0xc78c1d510052331aULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosGetDialogResultRequest";
  }

  static const char* value(const  ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
int32 dialogHandle\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosGetDialogResultResponse";
  }

  static const char* value(const  ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.dialogHandle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosGetDialogResultRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosGetDialogResultResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosGetDialogResult> {
  static const char* value() 
  {
    return "3a2c67a393403ca4628ae721d28678fb";
  }

  static const char* value(const vrep_common::simRosGetDialogResult&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosGetDialogResult> {
  static const char* value() 
  {
    return "vrep_common/simRosGetDialogResult";
  }

  static const char* value(const vrep_common::simRosGetDialogResult&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3a2c67a393403ca4628ae721d28678fb";
  }

  static const char* value(const vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosGetDialogResult";
  }

  static const char* value(const vrep_common::simRosGetDialogResultRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3a2c67a393403ca4628ae721d28678fb";
  }

  static const char* value(const vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosGetDialogResult";
  }

  static const char* value(const vrep_common::simRosGetDialogResultResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSGETDIALOGRESULT_H

