/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/vrep/vrep_common/srv/simRosGetCollisionHandle.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSGETCOLLISIONHANDLE_H
#define VREP_COMMON_SERVICE_SIMROSGETCOLLISIONHANDLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosGetCollisionHandleRequest_ {
  typedef simRosGetCollisionHandleRequest_<ContainerAllocator> Type;

  simRosGetCollisionHandleRequest_()
  : collisionName()
  {
  }

  simRosGetCollisionHandleRequest_(const ContainerAllocator& _alloc)
  : collisionName(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _collisionName_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  collisionName;


  typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosGetCollisionHandleRequest
typedef  ::vrep_common::simRosGetCollisionHandleRequest_<std::allocator<void> > simRosGetCollisionHandleRequest;

typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleRequest> simRosGetCollisionHandleRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleRequest const> simRosGetCollisionHandleRequestConstPtr;


template <class ContainerAllocator>
struct simRosGetCollisionHandleResponse_ {
  typedef simRosGetCollisionHandleResponse_<ContainerAllocator> Type;

  simRosGetCollisionHandleResponse_()
  : handle(0)
  {
  }

  simRosGetCollisionHandleResponse_(const ContainerAllocator& _alloc)
  : handle(0)
  {
  }

  typedef int32_t _handle_type;
  int32_t handle;


  typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosGetCollisionHandleResponse
typedef  ::vrep_common::simRosGetCollisionHandleResponse_<std::allocator<void> > simRosGetCollisionHandleResponse;

typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleResponse> simRosGetCollisionHandleResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosGetCollisionHandleResponse const> simRosGetCollisionHandleResponseConstPtr;

struct simRosGetCollisionHandle
{

typedef simRosGetCollisionHandleRequest Request;
typedef simRosGetCollisionHandleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosGetCollisionHandle
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cf86508d9f797a77ca9b0cab99fc61ca";
  }

  static const char* value(const  ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xcf86508d9f797a77ULL;
  static const uint64_t static_value2 = 0xca9b0cab99fc61caULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosGetCollisionHandleRequest";
  }

  static const char* value(const  ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
string collisionName\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "92535b678299d2bdda959704e78c275e";
  }

  static const char* value(const  ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x92535b678299d2bdULL;
  static const uint64_t static_value2 = 0xda959704e78c275eULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosGetCollisionHandleResponse";
  }

  static const char* value(const  ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 handle\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.collisionName);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosGetCollisionHandleRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.handle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosGetCollisionHandleResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosGetCollisionHandle> {
  static const char* value() 
  {
    return "c921683644719c386866fcd63b2e041d";
  }

  static const char* value(const vrep_common::simRosGetCollisionHandle&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosGetCollisionHandle> {
  static const char* value() 
  {
    return "vrep_common/simRosGetCollisionHandle";
  }

  static const char* value(const vrep_common::simRosGetCollisionHandle&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c921683644719c386866fcd63b2e041d";
  }

  static const char* value(const vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosGetCollisionHandle";
  }

  static const char* value(const vrep_common::simRosGetCollisionHandleRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c921683644719c386866fcd63b2e041d";
  }

  static const char* value(const vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosGetCollisionHandle";
  }

  static const char* value(const vrep_common::simRosGetCollisionHandleResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSGETCOLLISIONHANDLE_H

