/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/vrep/vrep_common/srv/simRosSynchronous.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSSYNCHRONOUS_H
#define VREP_COMMON_SERVICE_SIMROSSYNCHRONOUS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosSynchronousRequest_ {
  typedef simRosSynchronousRequest_<ContainerAllocator> Type;

  simRosSynchronousRequest_()
  : enable(0)
  {
  }

  simRosSynchronousRequest_(const ContainerAllocator& _alloc)
  : enable(0)
  {
  }

  typedef uint8_t _enable_type;
  uint8_t enable;


  typedef boost::shared_ptr< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosSynchronousRequest
typedef  ::vrep_common::simRosSynchronousRequest_<std::allocator<void> > simRosSynchronousRequest;

typedef boost::shared_ptr< ::vrep_common::simRosSynchronousRequest> simRosSynchronousRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosSynchronousRequest const> simRosSynchronousRequestConstPtr;


template <class ContainerAllocator>
struct simRosSynchronousResponse_ {
  typedef simRosSynchronousResponse_<ContainerAllocator> Type;

  simRosSynchronousResponse_()
  : result(0)
  {
  }

  simRosSynchronousResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosSynchronousResponse
typedef  ::vrep_common::simRosSynchronousResponse_<std::allocator<void> > simRosSynchronousResponse;

typedef boost::shared_ptr< ::vrep_common::simRosSynchronousResponse> simRosSynchronousResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosSynchronousResponse const> simRosSynchronousResponseConstPtr;

struct simRosSynchronous
{

typedef simRosSynchronousRequest Request;
typedef simRosSynchronousResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosSynchronous
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "34abd7794638063ef7576ad13e0da876";
  }

  static const char* value(const  ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x34abd7794638063eULL;
  static const uint64_t static_value2 = 0xf7576ad13e0da876ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosSynchronousRequest";
  }

  static const char* value(const  ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
uint8 enable\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosSynchronousResponse";
  }

  static const char* value(const  ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosSynchronousRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.enable);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosSynchronousRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosSynchronousResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosSynchronousResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosSynchronous> {
  static const char* value() 
  {
    return "ee99577c106b55d579549e7b24b16926";
  }

  static const char* value(const vrep_common::simRosSynchronous&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosSynchronous> {
  static const char* value() 
  {
    return "vrep_common/simRosSynchronous";
  }

  static const char* value(const vrep_common::simRosSynchronous&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosSynchronousRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ee99577c106b55d579549e7b24b16926";
  }

  static const char* value(const vrep_common::simRosSynchronousRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosSynchronousRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosSynchronous";
  }

  static const char* value(const vrep_common::simRosSynchronousRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosSynchronousResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ee99577c106b55d579549e7b24b16926";
  }

  static const char* value(const vrep_common::simRosSynchronousResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosSynchronousResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosSynchronous";
  }

  static const char* value(const vrep_common::simRosSynchronousResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSSYNCHRONOUS_H

