/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/vrep/vrep_common/srv/simRosRemoveObject.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSREMOVEOBJECT_H
#define VREP_COMMON_SERVICE_SIMROSREMOVEOBJECT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosRemoveObjectRequest_ {
  typedef simRosRemoveObjectRequest_<ContainerAllocator> Type;

  simRosRemoveObjectRequest_()
  : handle(0)
  {
  }

  simRosRemoveObjectRequest_(const ContainerAllocator& _alloc)
  : handle(0)
  {
  }

  typedef int32_t _handle_type;
  int32_t handle;


  typedef boost::shared_ptr< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosRemoveObjectRequest
typedef  ::vrep_common::simRosRemoveObjectRequest_<std::allocator<void> > simRosRemoveObjectRequest;

typedef boost::shared_ptr< ::vrep_common::simRosRemoveObjectRequest> simRosRemoveObjectRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosRemoveObjectRequest const> simRosRemoveObjectRequestConstPtr;


template <class ContainerAllocator>
struct simRosRemoveObjectResponse_ {
  typedef simRosRemoveObjectResponse_<ContainerAllocator> Type;

  simRosRemoveObjectResponse_()
  : result(0)
  {
  }

  simRosRemoveObjectResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosRemoveObjectResponse
typedef  ::vrep_common::simRosRemoveObjectResponse_<std::allocator<void> > simRosRemoveObjectResponse;

typedef boost::shared_ptr< ::vrep_common::simRosRemoveObjectResponse> simRosRemoveObjectResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosRemoveObjectResponse const> simRosRemoveObjectResponseConstPtr;

struct simRosRemoveObject
{

typedef simRosRemoveObjectRequest Request;
typedef simRosRemoveObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosRemoveObject
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "92535b678299d2bdda959704e78c275e";
  }

  static const char* value(const  ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x92535b678299d2bdULL;
  static const uint64_t static_value2 = 0xda959704e78c275eULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosRemoveObjectRequest";
  }

  static const char* value(const  ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
int32 handle\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosRemoveObjectResponse";
  }

  static const char* value(const  ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.handle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosRemoveObjectRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosRemoveObjectResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosRemoveObject> {
  static const char* value() 
  {
    return "6833353cd429b83819dab869600ce745";
  }

  static const char* value(const vrep_common::simRosRemoveObject&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosRemoveObject> {
  static const char* value() 
  {
    return "vrep_common/simRosRemoveObject";
  }

  static const char* value(const vrep_common::simRosRemoveObject&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6833353cd429b83819dab869600ce745";
  }

  static const char* value(const vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosRemoveObject";
  }

  static const char* value(const vrep_common::simRosRemoveObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6833353cd429b83819dab869600ce745";
  }

  static const char* value(const vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosRemoveObject";
  }

  static const char* value(const vrep_common::simRosRemoveObjectResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSREMOVEOBJECT_H

