/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/e2/e2_apps_rosbuild/highLevel_Interaction/msg/SpeakData.msg */
#ifndef HIGHLEVEL_INTERACTION_MESSAGE_SPEAKDATA_H
#define HIGHLEVEL_INTERACTION_MESSAGE_SPEAKDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "std_msgs/Int32.h"

namespace highLevel_Interaction
{
template <class ContainerAllocator>
struct SpeakData_ {
  typedef SpeakData_<ContainerAllocator> Type;

  SpeakData_()
  : header()
  , phraseNum()
  {
  }

  SpeakData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , phraseNum(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::std_msgs::Int32_<ContainerAllocator>  _phraseNum_type;
   ::std_msgs::Int32_<ContainerAllocator>  phraseNum;


  typedef boost::shared_ptr< ::highLevel_Interaction::SpeakData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::highLevel_Interaction::SpeakData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SpeakData
typedef  ::highLevel_Interaction::SpeakData_<std::allocator<void> > SpeakData;

typedef boost::shared_ptr< ::highLevel_Interaction::SpeakData> SpeakDataPtr;
typedef boost::shared_ptr< ::highLevel_Interaction::SpeakData const> SpeakDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::highLevel_Interaction::SpeakData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::highLevel_Interaction::SpeakData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace highLevel_Interaction

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::highLevel_Interaction::SpeakData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::highLevel_Interaction::SpeakData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::highLevel_Interaction::SpeakData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b6cff6f5fda3edef1242a7e3d5fe36e6";
  }

  static const char* value(const  ::highLevel_Interaction::SpeakData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb6cff6f5fda3edefULL;
  static const uint64_t static_value2 = 0x1242a7e3d5fe36e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::highLevel_Interaction::SpeakData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "highLevel_Interaction/SpeakData";
  }

  static const char* value(const  ::highLevel_Interaction::SpeakData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::highLevel_Interaction::SpeakData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
std_msgs/Int32 phraseNum\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
";
  }

  static const char* value(const  ::highLevel_Interaction::SpeakData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::highLevel_Interaction::SpeakData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::highLevel_Interaction::SpeakData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::highLevel_Interaction::SpeakData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.phraseNum);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SpeakData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::highLevel_Interaction::SpeakData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::highLevel_Interaction::SpeakData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "phraseNum: ";
s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.phraseNum);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HIGHLEVEL_INTERACTION_MESSAGE_SPEAKDATA_H

