/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/vrep/vrep_common/srv/simRosClearFloatSignal.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSCLEARFLOATSIGNAL_H
#define VREP_COMMON_SERVICE_SIMROSCLEARFLOATSIGNAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosClearFloatSignalRequest_ {
  typedef simRosClearFloatSignalRequest_<ContainerAllocator> Type;

  simRosClearFloatSignalRequest_()
  : signalName()
  {
  }

  simRosClearFloatSignalRequest_(const ContainerAllocator& _alloc)
  : signalName(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _signalName_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  signalName;


  typedef boost::shared_ptr< ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosClearFloatSignalRequest
typedef  ::vrep_common::simRosClearFloatSignalRequest_<std::allocator<void> > simRosClearFloatSignalRequest;

typedef boost::shared_ptr< ::vrep_common::simRosClearFloatSignalRequest> simRosClearFloatSignalRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosClearFloatSignalRequest const> simRosClearFloatSignalRequestConstPtr;


template <class ContainerAllocator>
struct simRosClearFloatSignalResponse_ {
  typedef simRosClearFloatSignalResponse_<ContainerAllocator> Type;

  simRosClearFloatSignalResponse_()
  : result(0)
  {
  }

  simRosClearFloatSignalResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosClearFloatSignalResponse
typedef  ::vrep_common::simRosClearFloatSignalResponse_<std::allocator<void> > simRosClearFloatSignalResponse;

typedef boost::shared_ptr< ::vrep_common::simRosClearFloatSignalResponse> simRosClearFloatSignalResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosClearFloatSignalResponse const> simRosClearFloatSignalResponseConstPtr;

struct simRosClearFloatSignal
{

typedef simRosClearFloatSignalRequest Request;
typedef simRosClearFloatSignalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosClearFloatSignal
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "00c43203ad474c6ce746089e83166bba";
  }

  static const char* value(const  ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x00c43203ad474c6cULL;
  static const uint64_t static_value2 = 0xe746089e83166bbaULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosClearFloatSignalRequest";
  }

  static const char* value(const  ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
string signalName\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosClearFloatSignalResponse";
  }

  static const char* value(const  ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.signalName);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosClearFloatSignalRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosClearFloatSignalResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosClearFloatSignal> {
  static const char* value() 
  {
    return "78c7f457aa3ca9421b43a9c08cf8400a";
  }

  static const char* value(const vrep_common::simRosClearFloatSignal&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosClearFloatSignal> {
  static const char* value() 
  {
    return "vrep_common/simRosClearFloatSignal";
  }

  static const char* value(const vrep_common::simRosClearFloatSignal&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "78c7f457aa3ca9421b43a9c08cf8400a";
  }

  static const char* value(const vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosClearFloatSignal";
  }

  static const char* value(const vrep_common::simRosClearFloatSignalRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "78c7f457aa3ca9421b43a9c08cf8400a";
  }

  static const char* value(const vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosClearFloatSignal";
  }

  static const char* value(const vrep_common::simRosClearFloatSignalResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSCLEARFLOATSIGNAL_H

