/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/vrep/vrep_common/srv/simRosSetJointTargetVelocity.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSSETJOINTTARGETVELOCITY_H
#define VREP_COMMON_SERVICE_SIMROSSETJOINTTARGETVELOCITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosSetJointTargetVelocityRequest_ {
  typedef simRosSetJointTargetVelocityRequest_<ContainerAllocator> Type;

  simRosSetJointTargetVelocityRequest_()
  : handle(0)
  , targetVelocity(0.0)
  {
  }

  simRosSetJointTargetVelocityRequest_(const ContainerAllocator& _alloc)
  : handle(0)
  , targetVelocity(0.0)
  {
  }

  typedef int32_t _handle_type;
  int32_t handle;

  typedef double _targetVelocity_type;
  double targetVelocity;


  typedef boost::shared_ptr< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosSetJointTargetVelocityRequest
typedef  ::vrep_common::simRosSetJointTargetVelocityRequest_<std::allocator<void> > simRosSetJointTargetVelocityRequest;

typedef boost::shared_ptr< ::vrep_common::simRosSetJointTargetVelocityRequest> simRosSetJointTargetVelocityRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosSetJointTargetVelocityRequest const> simRosSetJointTargetVelocityRequestConstPtr;


template <class ContainerAllocator>
struct simRosSetJointTargetVelocityResponse_ {
  typedef simRosSetJointTargetVelocityResponse_<ContainerAllocator> Type;

  simRosSetJointTargetVelocityResponse_()
  : result(0)
  {
  }

  simRosSetJointTargetVelocityResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosSetJointTargetVelocityResponse
typedef  ::vrep_common::simRosSetJointTargetVelocityResponse_<std::allocator<void> > simRosSetJointTargetVelocityResponse;

typedef boost::shared_ptr< ::vrep_common::simRosSetJointTargetVelocityResponse> simRosSetJointTargetVelocityResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosSetJointTargetVelocityResponse const> simRosSetJointTargetVelocityResponseConstPtr;

struct simRosSetJointTargetVelocity
{

typedef simRosSetJointTargetVelocityRequest Request;
typedef simRosSetJointTargetVelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosSetJointTargetVelocity
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a3f4b46893a91525225ffda04544130e";
  }

  static const char* value(const  ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa3f4b46893a91525ULL;
  static const uint64_t static_value2 = 0x225ffda04544130eULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosSetJointTargetVelocityRequest";
  }

  static const char* value(const  ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
int32 handle\n\
float64 targetVelocity\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosSetJointTargetVelocityResponse";
  }

  static const char* value(const  ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.handle);
    stream.next(m.targetVelocity);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosSetJointTargetVelocityRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosSetJointTargetVelocityResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosSetJointTargetVelocity> {
  static const char* value() 
  {
    return "4f4a9bd7fbc203cc2e92559ecddbacea";
  }

  static const char* value(const vrep_common::simRosSetJointTargetVelocity&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosSetJointTargetVelocity> {
  static const char* value() 
  {
    return "vrep_common/simRosSetJointTargetVelocity";
  }

  static const char* value(const vrep_common::simRosSetJointTargetVelocity&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4f4a9bd7fbc203cc2e92559ecddbacea";
  }

  static const char* value(const vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosSetJointTargetVelocity";
  }

  static const char* value(const vrep_common::simRosSetJointTargetVelocityRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4f4a9bd7fbc203cc2e92559ecddbacea";
  }

  static const char* value(const vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosSetJointTargetVelocity";
  }

  static const char* value(const vrep_common::simRosSetJointTargetVelocityResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSSETJOINTTARGETVELOCITY_H

