/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/vrep/vrep_common/srv/simRosAddStatusbarMessage.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSADDSTATUSBARMESSAGE_H
#define VREP_COMMON_SERVICE_SIMROSADDSTATUSBARMESSAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosAddStatusbarMessageRequest_ {
  typedef simRosAddStatusbarMessageRequest_<ContainerAllocator> Type;

  simRosAddStatusbarMessageRequest_()
  : message()
  {
  }

  simRosAddStatusbarMessageRequest_(const ContainerAllocator& _alloc)
  : message(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  message;


  typedef boost::shared_ptr< ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosAddStatusbarMessageRequest
typedef  ::vrep_common::simRosAddStatusbarMessageRequest_<std::allocator<void> > simRosAddStatusbarMessageRequest;

typedef boost::shared_ptr< ::vrep_common::simRosAddStatusbarMessageRequest> simRosAddStatusbarMessageRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosAddStatusbarMessageRequest const> simRosAddStatusbarMessageRequestConstPtr;


template <class ContainerAllocator>
struct simRosAddStatusbarMessageResponse_ {
  typedef simRosAddStatusbarMessageResponse_<ContainerAllocator> Type;

  simRosAddStatusbarMessageResponse_()
  : result(0)
  {
  }

  simRosAddStatusbarMessageResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosAddStatusbarMessageResponse
typedef  ::vrep_common::simRosAddStatusbarMessageResponse_<std::allocator<void> > simRosAddStatusbarMessageResponse;

typedef boost::shared_ptr< ::vrep_common::simRosAddStatusbarMessageResponse> simRosAddStatusbarMessageResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosAddStatusbarMessageResponse const> simRosAddStatusbarMessageResponseConstPtr;

struct simRosAddStatusbarMessage
{

typedef simRosAddStatusbarMessageRequest Request;
typedef simRosAddStatusbarMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosAddStatusbarMessage
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const  ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosAddStatusbarMessageRequest";
  }

  static const char* value(const  ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
string message\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosAddStatusbarMessageResponse";
  }

  static const char* value(const  ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.message);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosAddStatusbarMessageRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosAddStatusbarMessageResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosAddStatusbarMessage> {
  static const char* value() 
  {
    return "e9096ed5f063e7da83fbcb7332c6a56b";
  }

  static const char* value(const vrep_common::simRosAddStatusbarMessage&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosAddStatusbarMessage> {
  static const char* value() 
  {
    return "vrep_common/simRosAddStatusbarMessage";
  }

  static const char* value(const vrep_common::simRosAddStatusbarMessage&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e9096ed5f063e7da83fbcb7332c6a56b";
  }

  static const char* value(const vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosAddStatusbarMessage";
  }

  static const char* value(const vrep_common::simRosAddStatusbarMessageRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e9096ed5f063e7da83fbcb7332c6a56b";
  }

  static const char* value(const vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosAddStatusbarMessage";
  }

  static const char* value(const vrep_common::simRosAddStatusbarMessageResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSADDSTATUSBARMESSAGE_H

