/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/vrep/vrep_common/srv/simRosBreakForceSensor.srv */
#ifndef VREP_COMMON_SERVICE_SIMROSBREAKFORCESENSOR_H
#define VREP_COMMON_SERVICE_SIMROSBREAKFORCESENSOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace vrep_common
{
template <class ContainerAllocator>
struct simRosBreakForceSensorRequest_ {
  typedef simRosBreakForceSensorRequest_<ContainerAllocator> Type;

  simRosBreakForceSensorRequest_()
  : objectHandle(0)
  {
  }

  simRosBreakForceSensorRequest_(const ContainerAllocator& _alloc)
  : objectHandle(0)
  {
  }

  typedef int32_t _objectHandle_type;
  int32_t objectHandle;


  typedef boost::shared_ptr< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosBreakForceSensorRequest
typedef  ::vrep_common::simRosBreakForceSensorRequest_<std::allocator<void> > simRosBreakForceSensorRequest;

typedef boost::shared_ptr< ::vrep_common::simRosBreakForceSensorRequest> simRosBreakForceSensorRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosBreakForceSensorRequest const> simRosBreakForceSensorRequestConstPtr;


template <class ContainerAllocator>
struct simRosBreakForceSensorResponse_ {
  typedef simRosBreakForceSensorResponse_<ContainerAllocator> Type;

  simRosBreakForceSensorResponse_()
  : result(0)
  {
  }

  simRosBreakForceSensorResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int32_t _result_type;
  int32_t result;


  typedef boost::shared_ptr< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct simRosBreakForceSensorResponse
typedef  ::vrep_common::simRosBreakForceSensorResponse_<std::allocator<void> > simRosBreakForceSensorResponse;

typedef boost::shared_ptr< ::vrep_common::simRosBreakForceSensorResponse> simRosBreakForceSensorResponsePtr;
typedef boost::shared_ptr< ::vrep_common::simRosBreakForceSensorResponse const> simRosBreakForceSensorResponseConstPtr;

struct simRosBreakForceSensor
{

typedef simRosBreakForceSensorRequest Request;
typedef simRosBreakForceSensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct simRosBreakForceSensor
} // namespace vrep_common

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c941d9606c863e83c4461ed050c749de";
  }

  static const char* value(const  ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc941d9606c863e83ULL;
  static const uint64_t static_value2 = 0xc4461ed050c749deULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosBreakForceSensorRequest";
  }

  static const char* value(const  ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
int32 objectHandle\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const  ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosBreakForceSensorResponse";
  }

  static const char* value(const  ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 result\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.objectHandle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosBreakForceSensorRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct simRosBreakForceSensorResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<vrep_common::simRosBreakForceSensor> {
  static const char* value() 
  {
    return "b36b86ca13a59f09240c2d590a9babec";
  }

  static const char* value(const vrep_common::simRosBreakForceSensor&) { return value(); } 
};

template<>
struct DataType<vrep_common::simRosBreakForceSensor> {
  static const char* value() 
  {
    return "vrep_common/simRosBreakForceSensor";
  }

  static const char* value(const vrep_common::simRosBreakForceSensor&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b36b86ca13a59f09240c2d590a9babec";
  }

  static const char* value(const vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosBreakForceSensor";
  }

  static const char* value(const vrep_common::simRosBreakForceSensorRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b36b86ca13a59f09240c2d590a9babec";
  }

  static const char* value(const vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "vrep_common/simRosBreakForceSensor";
  }

  static const char* value(const vrep_common::simRosBreakForceSensorResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_SERVICE_SIMROSBREAKFORCESENSOR_H

