- id: 0
  name: AD
  position: [-2.0, -1.54, 0]
  orientation: [-0.73, 0.68]

- id: 1
  name: airlab
  position: [-0.948, -0.71, 0]
  orientation: [-0.69, 0.72]

- id: 2
  name: base
  position: [4.307, 2.726, 0]
  orientation: [-0.70, 0.70]
