/* Auto-generated by genmsg_cpp for file /home/jackal/ros_workspace/src/e2/e2_apps_rosbuild/head_analyzer/msg/EyesDataMSG.msg */
#ifndef HEAD_ANALYZER_MESSAGE_EYESDATAMSG_H
#define HEAD_ANALYZER_MESSAGE_EYESDATAMSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "std_msgs/Float32.h"
#include "std_msgs/Float32.h"

namespace head_analyzer
{
template <class ContainerAllocator>
struct EyesDataMSG_ {
  typedef EyesDataMSG_<ContainerAllocator> Type;

  EyesDataMSG_()
  : header()
  , eyeLRatio()
  , eyeRRatio()
  {
  }

  EyesDataMSG_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , eyeLRatio(_alloc)
  , eyeRRatio(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::std_msgs::Float32_<ContainerAllocator>  _eyeLRatio_type;
   ::std_msgs::Float32_<ContainerAllocator>  eyeLRatio;

  typedef  ::std_msgs::Float32_<ContainerAllocator>  _eyeRRatio_type;
   ::std_msgs::Float32_<ContainerAllocator>  eyeRRatio;


  typedef boost::shared_ptr< ::head_analyzer::EyesDataMSG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::head_analyzer::EyesDataMSG_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct EyesDataMSG
typedef  ::head_analyzer::EyesDataMSG_<std::allocator<void> > EyesDataMSG;

typedef boost::shared_ptr< ::head_analyzer::EyesDataMSG> EyesDataMSGPtr;
typedef boost::shared_ptr< ::head_analyzer::EyesDataMSG const> EyesDataMSGConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::head_analyzer::EyesDataMSG_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::head_analyzer::EyesDataMSG_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace head_analyzer

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::head_analyzer::EyesDataMSG_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::head_analyzer::EyesDataMSG_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::head_analyzer::EyesDataMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d40d8e3bb783a1495f8523b7fbc02d58";
  }

  static const char* value(const  ::head_analyzer::EyesDataMSG_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd40d8e3bb783a149ULL;
  static const uint64_t static_value2 = 0x5f8523b7fbc02d58ULL;
};

template<class ContainerAllocator>
struct DataType< ::head_analyzer::EyesDataMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "head_analyzer/EyesDataMSG";
  }

  static const char* value(const  ::head_analyzer::EyesDataMSG_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::head_analyzer::EyesDataMSG_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
std_msgs/Float32 eyeLRatio\n\
std_msgs/Float32 eyeRRatio\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const  ::head_analyzer::EyesDataMSG_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::head_analyzer::EyesDataMSG_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::head_analyzer::EyesDataMSG_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::head_analyzer::EyesDataMSG_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.eyeLRatio);
    stream.next(m.eyeRRatio);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EyesDataMSG_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::head_analyzer::EyesDataMSG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::head_analyzer::EyesDataMSG_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "eyeLRatio: ";
s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.eyeLRatio);
    s << indent << "eyeRRatio: ";
s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.eyeRRatio);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HEAD_ANALYZER_MESSAGE_EYESDATAMSG_H

